[ Iter1B ][ I #11 ][ PR #23 ] Updated Order class.
* Before this commit: All test cases were failing, output indicated that
  something was missing in the `Order` class.

* Added an `id` field with corresponding annotations to `Order` class, but
  test cases are still failing, output indicates that something is wrong
  with the `Recipe` class.

* Here is a portion of the test case failure output:
  `org.springframework.beans.factory.BeanCreationException: Error
  creating bean with name 'entityManagerFactory' defined in class path
  resource
  [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]:
  Invocation of init method failed; nested exception is
  javax.persistence.PersistenceException: [PersistenceUnit: default]
  Unable to build Hibernate SessionFactory; nested exception is
  org.hibernate.MappingException: Could not determine type for:
  edu.ncsu.csc.CoffeeMaker.models.Recipe, at table: order, for columns:
  [org.hibernate.mapping.Column(recipe)]`